services:
  pizza-frontend:
    build: .
    container_name: pizza-frontend-container
    ports:
      - "8080:80"  # Du erreichst die App unter http://localhost:8080
    volumes:
      - .:/usr/share/nginx/html # "Live-Reload": Code-Ã„nderungen sind sofort sichtbar
    restart: always